### ISSUE TITLE
what's the difference between CARD_SETS = ['00', '01']

### ISSUE THREAD

**Issue by 2811299** [redphx/artifact-cards-newtab#1]
black, red, blue, green ?
thank you very mush.

**Comment by redphx** [comment]
- `00` is Base set
- `01` is Call to Arms set  

You call https://playartifact.com/cardset/00 and https://playartifact.com/cardset/01 to get all the cards.

They are defined by Valve. Check [their API](https://github.com/ValveSoftware/ArtifactDeckCode) for more info.
